image: node:14.18.1
pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npm install --save-dev eslint-config-prettier
              - npx eslint .
            caches:
              - node
